---
title: "Calculate movement statistics"
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r setup, include=FALSE}
library(animovement)
library(tibble)
library(ggplot2)
library(dplyr, warn.conflicts = FALSE)
library(readxl)
library(here)
here::i_am("vignettes/articles/calculate-summary-statistics.Rmd")
```

```{r include=FALSE}
filepath_1 <- here("inst", "extdata", "multi", "GB_COM6_2021-08-05T15_37_55.csv")
filepath_2 <- here("inst", "extdata", "multi", "GB_COM7_2021-08-05T15_37_55.csv")
filepaths <- c(filepath_1, filepath_2)

df <- read_trackball(
  filepaths,
  setup = "of_free",
  col_time = 4,
  sampling_rate = 60,
  distance_scale = 394
)

# Smooth tracks
df_kinematics_clean <- df |>
  animovement::filter_na_speed() |> 
  mutate(x = animovement::replace_na(x, method = "stine"),
         y = animovement::replace_na(y, method = "stine")) |> 
  filter_movement(method = "rollmedian", window_width = 5, use_derivatives = TRUE) |> 
  calculate_kinematics()
```

Voilá! We've arrived at the final step, and all that's left is to calculate summary statistics! We can decide whether which measures of central tendency and dispersion (e.g. mean and SD). As most movement data is highly skewed, we  recommend to use median and MAD (default setting).

```{r}
library(tinytable)
df_kinematics_clean |>
  filter(v_translation > 0) |> 
  calculate_statistics(measures = "median_mad") |> 
  mutate(across(where(is.numeric), as.numeric)) |>
  tidyr::pivot_longer(where(is.numeric),
    names_to = "Measure",
    values_to = "Value"
  ) |> 
  select(-c("individual", "keypoint")) |> 
  tt() |>
  format_tt(digits = 2)
```


